-   id: yaspeller
    name: yaspeller
    entry: yaspeller
    language: node
    files: .*\.(md|markdown)$
    args: ["--find-repeat-words", "--ignore-digits", "--ignore-urls", "--ignore-uppercase"]
    require_serial: false
    additional_dependencies: []
